# AUTOGENERATED! DO NOT EDIT! File to edit: load_model.ipynb.

# %% auto 0
__all__ = ['pet_recognizer', 'categories', 'image', 'label', 'examples', 'intf', 'classify_img']

# %% load_model.ipynb 2
from fastai.vision.all import *

pet_recognizer = load_learner('./pet_recognizer.pkl')

# %% load_model.ipynb 6
categories = ("cat", "chihuahua", "chowchow", "pitbull", "shih tzu") # ordered based on file order (alphabetical)

def classify_img(img):
    pred, idx, probs = pet_recognizer.predict(img)
    return dict(zip(categories, map(float, probs)))

# %% load_model.ipynb 8
# Let's test out the Gradio interface

import gradio as gr

image = gr.Image()
label = gr.Label()

examples = ["siamese.jpeg"]

intf = gr.Interface(fn=classify_img, inputs=image, outputs=label, examples=examples)
intf.launch(inline=False)
